
spring.application.name=burger-api
server.port=9000

spring.datasource.url=jdbc:postgresql://ep-nameless-heart-apx4483p-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_RzBPirImv5W7

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.jdbc.bind=TRACE